version: "3"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: /run_server.sh
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgresc
    volumes:
      - postgres:/data/postgres
    ports:
      - "54322:5432"
    restart: unless-stopped

volumes:
  postgres:
