version: "3"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: /run_server.sh

  queue:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /run_queue.sh
